### ISSUE TITLE
Sir finding problem in Wikipedia when i said yes it's showing problem 

### ISSUE THREAD

**Issue by Shivam8552051878** [ismaan1998/Personal-assistant-in-Python#2]
![IMG20220331121317](https://user-images.githubusercontent.com/100829268/160992804-4e0cd3b6-6251-4fbb-a26b-7e1a7d886907.jpg)
This is the image of errror please solve sir

**Comment by ismaan1998** [comment]
in the output_module (line 4)
put **o** as **str(o)**
